[v0.9.1][Bugfix] Fix guided decoding invalid backend (#2645)
### What this PR does / why we need it?
Run:

```bash
pytest -sv tests/singlecard/test_guided_decoding.py
```

Come across an error:

```bash
FAILED tests/singlecard/test_guided_decoding.py::test_guided_json_completion[guidance:disable-any-whitespace] - NotImplementedError: VLLM_USE_V1=1 is not supported with --guided-decoding-backend=guidance:disable-any-whitespace.
FAILED tests/singlecard/test_guided_decoding.py::test_guided_regex[guidance:disable-any-whitespace] - NotImplementedError: VLLM_USE_V1=1 is not supported with --guided-decoding-backend=guidance:disable-any-whitespace.
```

### How was this patch tested?

Run:

```bash
pytest -sv tests/singlecard/test_guided_decoding.py
```

Output:

```bash
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.10.18, pytest-8.4.1, pluggy-1.6.0
rootdir: /home/sss/github/vllm-v0.9.1/vllm-ascend
configfile: pytest.ini
plugins: anyio-4.10.0, mock-3.14.1
collected 8 items                                                                                                                                                         

tests/singlecard/test_guided_decoding.py ss.ss..s                                                                                                                   [100%]

============================================================================ warnings summary =============================================================================
<frozen importlib._bootstrap>:241
  <frozen importlib._bootstrap>:241: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute

<frozen importlib._bootstrap>:241
  <frozen importlib._bootstrap>:241: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute

../../../miniconda3/envs/vllm-v0.9.1/lib/python3.10/site-packages/torch_npu/dynamo/torchair/__init__.py:8
  /home/sss/miniconda3/envs/vllm-v0.9.1/lib/python3.10/site-packages/torch_npu/dynamo/torchair/__init__.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================== 3 passed, 5 skipped, 3 warnings in 193.21s (0:03:13) ===========================================================
```

---------

Signed-off-by: shen-shanshan <467638484@qq.com>